feat: add trivy scan

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,59 +26,61 @@ jobs:
           java-version: '21'
           distribution: 'temurin'
 
-      # # Gitleaks scan (before compilation)
-      # - name: Run Gitleaks scan
-      #   uses: zricethezav/gitleaks-action@v2
+      # Gitleaks scan (before compilation)
+      - name: Run Gitleaks scan
+        uses: zricethezav/gitleaks-action@v2
+        with:
+          args: detect --source . --commit=HEAD --report-format=sarif --report-path=results.sarif
        
-      # # Upload the Gitleaks report
-      # - name: Upload Gitleaks report
-      #   uses: actions/upload-artifact@v4
+      # Upload the Gitleaks report
+      - name: Upload Gitleaks report
+        uses: actions/upload-artifact@v4
+        with:
+          name: gitleaks-report
+          path: results.sarif
+
+
+      #   # Compile Java code
+      # - name: Compile Java
+      #   run: mvn compile
+
+      # # Build Maven
+      # - name: Build Java project with Maven
+      #   run: mvn clean package
+
+      # # Login Docker Hub
+      # - name: Login to Docker Hub
+      #   uses: docker/login-action@v2
       #   with:
-      #     name: gitleaks-report
-      #     path: results.sarif
+      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
+      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
 
+      # #  Build Docker image
+      # - name: Build Docker image
+      #   run: docker build -t $DOCKER_IMAGE_NAME .
 
-        # Compile Java code
-      - name: Compile Java
-        run: mvn compile
+      # #  Test  Docker image
+      # - name: Test Docker image locally
+      #   run: |
+      #     docker run -d --name democyber-test -p 8080:8080 $DOCKER_IMAGE_NAME
+      #     sleep 10
+      #     curl -f http://localhost:8080 || echo "App not responding"
+      #     docker stop democyber-test
+      #     docker rm democyber-test
+      # - name: Build Docker image
+      #   run: docker build -t democyber:latest .
 
-      # Build Maven
-      - name: Build Java project with Maven
-        run: mvn clean package
+      # #Tivy scan
+      # - name: Build Docker image
+      #   run: docker build -t democyber:latest .
 
-      # Login Docker Hub
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      #  Build Docker image
-      - name: Build Docker image
-        run: docker build -t $DOCKER_IMAGE_NAME .
-
-      #  Test  Docker image
-      - name: Test Docker image locally
-        run: |
-          docker run -d --name democyber-test -p 8080:8080 $DOCKER_IMAGE_NAME
-          sleep 10
-          curl -f http://localhost:8080 || echo "App not responding"
-          docker stop democyber-test
-          docker rm democyber-test
-      - name: Build Docker image
-        run: docker build -t democyber:latest .
-
-      #Tivy scan
-      - name: Build Docker image
-        run: docker build -t democyber:latest .
-
-      - name: Scan Docker image with Trivy
-        uses: aquasecurity/trivy-action@0.20.0
-        with:
-          image-ref: democyber:latest
-          format: 'table'
-          exit-code: '0'   # fail if critical issues found
-          severity: 'CRITICAL,HIGH'
+      # - name: Scan Docker image with Trivy
+      #   uses: aquasecurity/trivy-action@0.20.0
+      #   with:
+      #     image-ref: democyber:latest
+      #     format: 'table'
+      #     exit-code: '0'   # fail if critical issues found
+      #     severity: 'CRITICAL,HIGH'
 
 
       # #  Push Docker image sur Docker Hub
