fix: update cicd to use upload artifactv4

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,27 +26,29 @@ jobs:
           java-version: '21'
           distribution: 'temurin'
 
-      #  Gitleaks scan (avant compilation)
-      - name: Install Gitleaks
-        run: |
-          curl -L -o gitleaks.tar.gz https://github.com/zricethezav/gitleaks/releases/download/v9.22.1/gitleaks_9.22.1_linux_x64.tar.gz
-          tar -xzf gitleaks.tar.gz
-          chmod +x gitleaks
-          ./gitleaks version  
 
-
+       # Gitleaks scan (avant compilation)
       - name: Run Gitleaks scan
-        run: |
-          ./gitleaks detect --source . --report-format json --report-path gitleaks-report.json
-          if [ -s gitleaks-report.json ]; then
-            echo "Secrets detected! Failing the pipeline."
-            exit 1
-          fi
+        uses: zricethezav/gitleaks-action@v2
+        with:
+          format: json
+          output: gitleaks-report.json
+          path: .
+
+      # Upload du rapport Gitleaks
       - name: Upload Gitleaks report
         uses: actions/upload-artifact@v4
         with:
           name: gitleaks-report
           path: gitleaks-report.json
+
+      # Vérifier si des secrets ont été détectés et échouer le pipeline
+      - name: Fail if secrets detected
+        run: |
+          if [ -s gitleaks-report.json ]; then
+            echo "Secrets detected! Failing the pipeline."
+            exit 1
+          fi
 
       # # Compile Java code
       # - name: Compile Java
